include(shared_functions.cmake)
function(bhh_assets_generate_dbs db_path assets)
  bhh_assets_get_scripts_dir(scripts_dir)
  separate_arguments(_assets UNIX_COMMAND ${assets})
  target_compile_definitions(bhh_sqlite3_game_assets_creator PUBLIC BHH_ASSET_PACKER_DB_SAVE_PATH="${db_path}")
  execute_process(COMMAND ${CMAKE_COMMAND} -S ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/key-converter -B ${CMAKE_BINARY_DIR}/${scripts_dir}/key-converter -G ${CMAKE_GENERATOR} RESULT_VARIABLE error_code)
  if (error_code AND NOT error_code EQUAL 0)
    message(FATAL_ERROR "Failed to build scripts")
  endif()
  execute_process(COMMAND ${CMAKE_COMMAND} --build ${CMAKE_BINARY_DIR}/${scripts_dir}/key-converter RESULT_VARIABLE error_code)
  if (error_code AND NOT error_code EQUAL 0)
    message(FATAL_ERROR "Failed to compile scripts")
  endif()
  set(all_keys "")
  set(db_files "")
  message(STATUS ${assets})
  foreach(item IN LISTS _assets)
    message(STATUS "Processing ${item}")
    get_filename_component(db_dir_name ${item} NAME)
    if (${db_dir_name} STREQUAL "")
      message(FATAL_ERROR "Bad path. Don't add `/` to the end of the path please.")
    endif()
    cmake_path(APPEND db_full_path "${db_path}" "${db_dir_name}")
    LIST(APPEND db_files ${db_full_path})
    execute_process(COMMAND ${CMAKE_BINARY_DIR}/${scripts_dir}/key-converter/bhh_sqlite3_game_assets_key_converter ${item} RESULT_VARIABLE error_code OUTPUT_VARIABLE output)
    if (error_code AND NOT error_code EQUAL 0)
      message(FATAL_ERROR "Failed to run key_converter")
    endif()
    string(CONCAT all_keys ${all_keys} ${output})
  endforeach()
  string(LENGTH ${all_keys} all_keys_len)
  math(EXPR all_keys_len "${all_keys_len}-1")
  string(SUBSTRING "${all_keys}" 0 ${all_keys_len} all_keys) # For some reason gcc now hates comma at the end of the list
  #file(REMOVE_RECURSE ${CMAKE_BINARY_DIR}/${scripts_dir}/key-converter)
  target_compile_definitions(bhh_sqlite3_game_assets PUBLIC BHH_ASSET_PACKER_ALL_KEYS=${all_keys})
  add_custom_target(bhh_sqlite3_game_assets_creator_run ALL VERBATIM
  COMMAND ${CMAKE_BINARY_DIR}/${scripts_dir}/asset-creator/bhh_sqlite3_game_assets_creator ${_assets}
  BYPRODUCTS ${db_files}
  DEPENDS bhh_sqlite3_game_assets_creator
  )
endfunction()
